
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rotate-pages
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 192.168.211.38
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rotate-pages
                port:
                  number: 8080
