
apiVersion: v2
kind: Service
metadata:
  name: rotate-pages
  namespace: rotate-pages
spec:
  selector:
    app: rotate-pages
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # Match the port where your Go application is running
      nodePort: 32001
