name: Build and Push Docker Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: upload-file
      IMAGE_TAG: ${{ github.repository }}:${{ github.sha }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: datthanhdgw/rotate-pages:${{ github.sha }},datthanhdgw/rotate-pages:latest
  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Update Image Tag Values
        run: |
          chart_dir="helm"
          new_image_tag=${{ github.sha }}

          # Update the values.yaml file with the new image tag
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"
      
      # - name: Commit the changes made
      #   run: | 
      #     git config --global user.name 'datthanhdgw'
      #     git config --global user.email 'datthanh.dgw@gmail.com'
      #     git commit -am "updating image tag"
      #     git push "https://x-access-token:${{ secrets.REGISTRY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          